server {
    listen 8000;
    server_name localhost;

    # 1. Routing untuk User Service (Node.js)
    location /api/users/ {
        # Menghapus prefix /api/users saat diteruskan ke Node.js jika diperlukan, 
        # tapi karena di server.js kita pakainya langsung /register dan /login, 
        # kita rewrite jalurnya agar pas.
        rewrite ^/api/users/(.*)$ /$1 break;

        proxy_pass http://user-service:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/products {
        # Laravel secara default sudah mendengarkan di jalur /api/products, 
        # jadi kita tinggal teruskan langsung tanpa rewrite.
        proxy_pass http://product-service:8002/api/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/cart {
    proxy_pass http://cart-service:8003;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;
}

location /api/orders {
    proxy_pass http://order-service:8004;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;
}


location /api/payments {
    proxy_pass http://payment-service:8005;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;
}
}